version: "3.8"
services:
  frontend:
    build: .
    container_name: frontend-raspi
    ports:
      - "5173:5173"
    volumes:
      - ./runtime-config/config.js:/usr/share/nginx/html/config.js:ro
    restart: unless-stopped 